Fix PNG aliasing
tobie/specref pull request #759
Opened 2023-10-12 17:15 UTC by tobie

Closes #758

/cc @svgeesus 

I think this is what you're asking for. Leverages an undocumented (sorry) feature to force overwrites for exactly those usecases.

2023-10-12 19:45 UTC, tobie commented
Something's off unfortunately. How urgent is this?

2023-10-12 20:28 UTC, svgeesus commented
No rush, I just happened to notice it in a spec today, so raised the issue before I forgot.

2023-10-13 05:53 UTC, deniak requested changes
The PNG2e alias should also be updated in `refs/biblio.json`:
```
     "PNG2e": {
         "aliasOf": "PNG-1"
     },
```

2023-10-13 05:53 UTC, deniak commented on refs/w3c.json
> +    },
I think the main issue is a mix of uppercase/lowercase shortnames and a missing version"

```suggestion
    "PNG-19961001": {
        "aliasOf": "PNG-1-19961001"
    },
    "PNG-20030520": {
        "aliasOf": "PNG-1-20030520"
    },
    "PNG-20031110": {
        "aliasOf": "PNG-1-20031110"
    },
```

2023-10-13 05:53 UTC, deniak commented on refs/w3c.json
> +    },
Not needed since we already have `PNG-1`

```suggestion
```

2023-10-13 05:59 UTC, deniak commented
@tobie, I made some suggestions which I believe should work.
I see specref still relies on tr.rdf which we plan to retire in the future. Indeed, tr.rdf has some limitations and doesn't show data related to the specification series. Instead, the [W3C API](https://w3c.github.io/w3c-api/) provides more details, e.g. https://api.w3.org/specification-series/png.

That said, I'm aware upgrading specref to use the API isn't a priority but I'm just mentioning in case we can find someone to work on that.

2023-10-13 06:14 UTC, tobie commented
Thanks @deniak. Your changes would be overwritten on next update, unfortunately.

2023-10-13 07:18 UTC, deniak commented
> Thanks @deniak. Your changes would be overwritten on next update, unfortunately.

Right, I forgot the references get automatically updated.
Changing the `newId` for `PNG` in `overwrites/w3c.json` should do the trick I guess:
```
  { "id": "PNG",               "action": "renameTo", "newId": "PNG-1"},
  { "id": "PNG",               "action": "createAlias", "aliasOf": "png-3"}
```

2023-10-13 07:20 UTC, tobie commented
Have you tried it? I wasn’t working for me yesterday.

2023-10-13 07:22 UTC, deniak commented
> Have you tried it? It wasn’t working for me yesterday.

I just gave it a try and it seems to work.
I don't have write access to the repo, but I'm happy to open a new PR if you want.

2023-10-13 07:24 UTC, tobie commented
Adding your changes here would be easier.

2023-10-13 07:50 UTC, deniak commented
> Adding your changes here would be easier.

Done.

2023-10-13 07:51 UTC, tobie commented
Sorry, I hadn't thought this through much and didn't consider you'd have to force push to clean things up. Apologies!

2023-10-13 07:52 UTC, deniak commented
no worries :)

2023-10-13 09:33 UTC, merged

2023-10-13 09:35 UTC, deniak commented
Thanks @tobie

2023-10-13 09:35 UTC, tobie commented
No, thank you!